#! /bin/sh
grep '1.' $1 | sort | cut -d. -f2- | sed '/  /s//\\I\{/' | sed '/:/s//\}/' > cat1.tex
grep '2.' $1 | sort | cut -d. -f2- | sed '/  /s//\\I\{/' | sed '/:/s//\}/' > cat2.tex
pdflatex -halt-on-error pbt.tex

